#!/bin/bash
#edit by www.jbxue.com
eth=$1

#out1=$(cat /proc/net/dev | grep ccinet0:)
out1=$(cat /proc/net/dev)
#out1=$(cat /proc/net/dev | grep lo:)
sleep 1

#out2=$(cat /proc/net/dev | grep ccinet0:)
out2=$(cat /proc/net/dev)
#out2=$(cat /proc/net/dev | grep lo:)
echo "$out1;$out2"

exit 0